// Does the build we are running match the save we are running it on?
//
//   run profilecheck.js          # once, from boot.js, before anything else starts
//
// COMPILED SOURCE. `caps/build-profile.js` is a VIRTUAL module generated by
// tools/compile/build.mjs from the profile it built for — so every dist carries
// the identity of its own regime, and this file needs no build-time constants
// and no minify flags to read it.
//
// ---------------------------------------------------------------------------
// Why this file has to exist at all.
//
// A capability compiler moves a gate from run time to link time, and in doing
// so it moves the failure. The handwritten autobuy-sing.js re-asserted
// `canUseSingularity` on entry, so running it in the wrong BitNode produced a
// sentence naming the cause. A compiled dist has no such check — the fact that
// the file exists IS the assertion — so a dist built for the wrong profile
// fails in one of two ways:
//
//   too much capability   compiled for "has SF4" and we do not:
//                         ns.singularity.* throws on first call. Loud, but only
//                         in a one-shot helper's status file, and only once
//                         something tries to buy. Hours, not days.
//
//   too little capability compiled for "no SF4" and we have it:
//                         NOTHING throws. autobuy takes the terminal route, go
//                         never cheats, the whole stack runs slightly worse
//                         forever and reports itself perfectly healthy. This is
//                         the shape CLAUDE.md calls the most expensive class of
//                         bug in this repo, and a build step ADDS it. Nothing
//                         downstream can detect it, because nothing downstream
//                         knows what it is missing.
//
// So this is not decoration; it is the thing that makes a build step safe to
// adopt at all. It costs 1GB, runs once per life, and its predicate does not
// depend on anything the build produced (invariant C4): it asks the GAME what
// Source-Files exist and compares against a manifest baked into the dist.
//
// It re-derives the capabilities through sfgate.js — the same module the build
// used — rather than comparing stamps. A stamp comparison would pass in the
// case where the dist is old and sfgate has since been CORRECTED, which is
// precisely the go.js `sf14 >= 2` bug arriving a second time by another road.

import { canUseSingularity, canUseGoCheat, canUseGang, canUseSleeve, canUseCorporation, canUseBladeburner, canUseGrafting, hasHacknetServers, hasStaneksGift, canShortStock, canUseStockOrders, canReadBitNodeMultipliers } from 'sfgate.js'
import { BUILD_STAMP, BUILD_CAPS, BUILD_FILES } from 'caps/build-profile.js'

const STATUS = '/tel/profilecheck.txt'

// name -> predicate, in the same order build.mjs derives them. A capability the
// build knows about and this table does not would make the check silently
// narrower than the thing it guards, so build.mjs refuses to build if the two
// lists disagree.
const PREDICATES = {
  CAP_SINGULARITY: canUseSingularity,
  CAP_GO_CHEAT: canUseGoCheat,
  CAP_GANG: canUseGang,
  CAP_SLEEVE: canUseSleeve,
  CAP_CORPORATION: canUseCorporation,
  CAP_BLADEBURNER: canUseBladeburner,
  CAP_GRAFTING: canUseGrafting,
  CAP_HACKNET_SERVERS: hasHacknetServers,
  CAP_STANEK: hasStaneksGift,
  CAP_STOCK_SHORT: canShortStock,
  CAP_STOCK_ORDERS: canUseStockOrders,
  CAP_BN_MULTS: canReadBitNodeMultipliers,
}

export async function main(ns) {
  ns.disableLog('ALL')

  // One 1GB read. Everything below is pure.
  let reset = null
  let readError = null
  try {
    reset = ns.getResetInfo()
  } catch (err) {
    readError = String(err).slice(0, 200)
  }

  // "I could not check" is NOT "it is fine" — the distinction verify-deploy
  // encodes as exit 2. Say so in as many words rather than exiting quietly.
  if (!reset) {
    const msg = `profilecheck: COULD NOT CHECK — ns.getResetInfo() failed: ${readError}`
    ns.write(STATUS, JSON.stringify({ at: new Date().toISOString(), health: 'unknown', build: BUILD_STAMP, detail: msg }, null, 2), 'w')
    ns.tprint(`!!!!! ${msg}`)
    return
  }

  const lost = []    // build says no, save says yes -> SILENT capability loss
  const missing = [] // build says yes, save says no -> will throw on first call
  for (const name of Object.keys(PREDICATES)) {
    const live = !!PREDICATES[name](reset)
    if (!!BUILD_CAPS[name] === live) continue
    if (live) lost.push(name)
    else missing.push(name)
  }

  // A second, independent question: is the dist actually complete? A partial
  // push leaves go.js compiled to exec go-cheat.js while go-cheat.js is absent,
  // which no capability comparison can see. ns.fileExists is 0.1GB.
  const absent = BUILD_FILES.filter((f) => !ns.fileExists(f, 'home'))

  const liveStamp = stamp(reset)
  const ok = lost.length === 0 && missing.length === 0 && absent.length === 0

  const report = {
    at: new Date().toISOString(),
    health: ok ? 'ok' : 'error',
    build: BUILD_STAMP,
    live: liveStamp,
    lost,
    missing,
    absent,
    detail: ok
      ? `build ${BUILD_STAMP} matches this save, all ${BUILD_FILES.length} files present`
      : [
          lost.length ? `built WITHOUT ${lost.join(', ')} but this save HAS them — capability is being lost SILENTLY; rebuild with --bitnode ${reset.currentNode}` : null,
          missing.length ? `built WITH ${missing.join(', ')} but this save does NOT have them — those calls will throw; rebuild with --bitnode ${reset.currentNode}` : null,
          absent.length ? `dist is incomplete, missing from home: ${absent.join(', ')}` : null,
        ].filter(Boolean).join(' | '),
  }

  ns.write(STATUS, JSON.stringify(report, null, 2), 'w')

  // Loud on the terminal, not only in a file. The silent arm is the one that
  // needs this: a stack that runs is a stack nobody investigates.
  if (!ok) ns.tprint(`!!!!! profilecheck: build ${BUILD_STAMP} vs save ${liveStamp} — ${report.detail}`)
  else ns.tprint(`profilecheck: build ${BUILD_STAMP} matches this save`)
}

/** `bn4/sf1.1`, the same construction profile.mjs stampOf() uses. */
function stamp(reset) {
  const parts = []
  for (const [n, lvl] of reset.ownedSF ?? []) if (lvl > 0) parts.push([n, lvl])
  parts.sort((a, b) => a[0] - b[0])
  return [`bn${reset.currentNode}`, ...parts.map(([n, lvl]) => `sf${n}.${lvl}`)].join('/')
}
