// STAGED ns.ramOverride REWRITE of createProgram.js.
//
// Generated by tools/staging/ramoverride/stage.mjs from the shipped createProgram.js.
// The original `main` body is preserved BYTE FOR BYTE as `act(ns)`; the only
// change is how this file declares its RAM. Pre-existing defects in the logic
// (docs/game-knowledge.md §1) are deliberately NOT fixed here.
//
// ---------------------------------------------------------------------------
// RAMOVERRIDE 2.6GB — excludes: ns.singularity.createProgram (5GB base / 80GB at SF4.1) and ns.singularity.isBusy (0.5/8GB), plus the ns.spawn/kill/ps/hacknet reads common.js's runCallbackExit and killOtherInstances pull in — none reachable until the SF4 gate below passes.
//
// Why this is sound: Netscript bills a script for every ns identifier in its
// import graph whether or not the call is reachable (RamCalculations.ts:407
// prices Identifier nodes, findFunc at :225-243 matches bare names), but only
// CALLING a Source-File-gated function throws. So this file may carry the
// references, declare 2.6GB, refuse to act when sfgate.js says it cannot, and be
// correct — instead of being unloadable in every BitNode that cannot use it.
//
// 2.6 = RamCostConstants.Base (1.6) + ns.getResetInfo (1.0). That is everything
// called before the capability decision: sfgate.js is pure, status.js touches
// only ns.write (0GB), and atExit / tprint / print / flags are all 0GB.
//
// When the capability IS present the allocation is raised to the file's FULL
// static price before anything expensive runs, because `dynamicRamUsage` only
// rises and crossing the allocation kills the script
// (NetscriptHelpers.tsx:498-520). A raise the host cannot afford is SILENTLY
// DENIED (NetscriptFunctions.ts:1210-1214 returns the old value), which is why
// it goes through ramgrow.js and why this file returns rather than continuing.
//
// Registered in tools/sim/bncheck.mjs STRUCTURAL. Asserted by
// tools/test/ramoverride.test.mjs [R1..R5]: the game's own calculator prices
// this file in four regimes and the suite fails if the override is ignored or
// if RAISE_CEILING does not reach the full static price.
// ---------------------------------------------------------------------------
import { runCallbackExit } from "common.js"
import { canUseSingularity, singularityRamMultiplier } from 'sfgate.js'
import { reporter } from 'status.js'
import { raiseRam } from 'ramgrow.js'

const RAMOVERRIDE_STATUS = '/tel/createProgram.txt'

/** This file's FULL static price as a function of the Singularity RAM
 *  multiplier (sfgate.js:71-77 — 1 inside BN4, 16 at SF4.1, 4 at SF4.2, 1 at
 *  SF4.3). 7.25 = everything not under ns.singularity; 5.5 = the
 *  ns.singularity surface at base price. Both measured with the game's own
 *  calculator and re-checked on every run by ramoverride.test.mjs [R5]. */
const RAISE_CEILING = (mult) => 7.25 + 5.5 * mult

export async function main(ns) {
  ns.ramOverride(2.6)

  const rerrors = []
  const note = reporter(ns, RAMOVERRIDE_STATUS, () => ({ errors: rerrors.slice(-5) }))
  ns.atExit(() => note.exit('stopped', { detail: 'createProgram.js exited' }))

  // Ask the GAME what this save can do, through the shared rules. Not a
  // try/catch around the namespace: RAM is billed before a line executes, so
  // such a guard can never fire (CLAUDE.md, "a guard that can never fire").
  const info = ns.getResetInfo()
  if (!canUseSingularity(info)) {
    note('waiting', {
      result: 'capability-absent',
      gate: 'canUseSingularity',
      bitNode: info.currentNode,
      detail:
        'canUseSingularity() is false for this save, so createProgram.js cannot act. Staying at the 2.6GB floor ' +
        'instead of reserving its full price. Create programs by hand: Terminal tab -> Create Program, pick the highest one your hacking level allows. It needs a trusted click (ProgramsRoot.tsx:96,108), so no script can do it without Source-File 4.',
    })
    return
  }

  const want = RAISE_CEILING(singularityRamMultiplier(info))
  if (!(await raiseRam(ns, want, RAMOVERRIDE_STATUS, 'createProgram.js needs its full allocation before the first gated call'))) return

  try {
    note('ok', { result: 'running', allocation: want, detail: 'allocation raised; running the original body' })
    await act(ns)
    note('ok', { result: 'finished', detail: 'createProgram.js returned normally' })
  } catch (err) {
    rerrors.push(`${new Date().toISOString()} ${err}`)
    note('error', { result: 'error', detail: String(err) })
    throw err
  }
}



const intelligence_exp_divisor = 200
const milliseconds_per_twenty_hours = 72000000
const milliseconds_per_ten_hours = 36000000
const milliseconds_per_eight_hours = 28800000
const milliseconds_per_four_hours = 14400000
const milliseconds_per_two_hours = 7200000
const milliseconds_per_hour = 3600000
const milliseconds_per_half_hour = 1800000
const milliseconds_per_quarter_hour = 900000
const milliseconds_per_five_minutes = 300000

export const programs = {
    "NUKE.exe": {
        hacking_level_required: 1,
        intelligence_exp: 1 / intelligence_exp_divisor,
        time: milliseconds_per_five_minutes,
        intelligence_exp_per_millisecond: 1 / intelligence_exp_divisor / milliseconds_per_five_minutes
    },
    "BruteSSH.exe": {
        hacking_level_required: 50,
        intelligence_exp: 50 / intelligence_exp_divisor,
        time: milliseconds_per_five_minutes * 2,
        intelligence_exp_per_millisecond: 50 / intelligence_exp_divisor / (milliseconds_per_five_minutes * 2),
        price: 500e3,
        port_program: true
    },
    "FTPCrack.exe": {
        hacking_level_required: 100,
        intelligence_exp: 100 / intelligence_exp_divisor,
        time: milliseconds_per_half_hour,
        intelligence_exp_per_millisecond: 100 / intelligence_exp_divisor / milliseconds_per_half_hour,
        price: 1500e3,
        port_program: true
    },
    "relaySMTP.exe": {
        hacking_level_required: 250,
        intelligence_exp: 250 / intelligence_exp_divisor,
        time: milliseconds_per_two_hours,
        intelligence_exp_per_millisecond: 250 / intelligence_exp_divisor / milliseconds_per_two_hours,
        price: 5e6,
        port_program: true
    },
    "HTTPWorm.exe": {
        hacking_level_required: 500,
        intelligence_exp: 500 / intelligence_exp_divisor,
        time: milliseconds_per_four_hours,
        intelligence_exp_per_millisecond: 500 / intelligence_exp_divisor / milliseconds_per_four_hours,
        price: 30e6,
        port_program: true
    },
    "SQLInject.exe": {
        hacking_level_required: 750,
        intelligence_exp: 750 / intelligence_exp_divisor,
        time: milliseconds_per_eight_hours,
        intelligence_exp_per_millisecond: 750 / intelligence_exp_divisor / milliseconds_per_eight_hours,
        price: 250e6,
        port_program: true
    },
    "DeepscanV1.exe": {
        hacking_level_required: 75,
        intelligence_exp: 75 / intelligence_exp_divisor,
        time: milliseconds_per_quarter_hour,
        intelligence_exp_per_millisecond: 75 / intelligence_exp_divisor / milliseconds_per_quarter_hour,
        price: 500000
    },
    "DeepscanV2.exe": {
        hacking_level_required: 400,
        intelligence_exp: 400 / intelligence_exp_divisor,
        time: milliseconds_per_two_hours,
        intelligence_exp_per_millisecond: 400 / intelligence_exp_divisor / milliseconds_per_two_hours,
        price: 25e6
    },
    "ServerProfiler.exe": {
        hacking_level_required: 75,
        intelligence_exp: 75 / intelligence_exp_divisor,
        time: milliseconds_per_half_hour,
        intelligence_exp_per_millisecond: 75 / intelligence_exp_divisor / milliseconds_per_half_hour,
        price: 1e6
    },
    "AutoLink.exe": {
        hacking_level_required: 25,
        intelligence_exp: 25 / intelligence_exp_divisor,
        time: milliseconds_per_quarter_hour,
        intelligence_exp_per_millisecond: 25 / intelligence_exp_divisor / milliseconds_per_quarter_hour,
        price: 1e6
    },
    "b1t_flum3.exe": {
        hacking_level_required: 1,
        intelligence_exp: 1 / intelligence_exp_divisor,
        time: milliseconds_per_five_minutes / 20,
        intelligence_exp_per_millisecond: 1 / intelligence_exp_divisor / milliseconds_per_five_minutes / 20
    }
}

const EPSILON_WAIT_TIME = 1000

function usage(ns) {
    ns.tprint(`Usage: run createProgram.js [--program] &lt${Object.keys(programs).concat(["all"]).join('|')}&gt [[--callback] &ltscript&gt]`)
}

export function getCreateProgramTasks(ns) {
    return Object.keys(programs).filter(program => !ns.fileExists(program, "home"))
        // `player.skills.hacking`, NOT `player.hacking_skill`. The flat stat
        // fields have not existed since v1; ns.getPlayer() builds its payload by
        // hand at NetscriptFunctions.ts:1371-1389 and puts skills under
        // `skills`. The old read made this `undefined >= n`, which is always
        // false, so this function returned {} unconditionally — and the caller
        // at :229 does `.shift()` on those keys, producing
        // `createProgram(undefined)`. Dormant only because this script is in
        // neither boot.js's STACK nor watchdog.js's WATCHED.
        .filter(program => ns.getPlayer().skills.hacking >= programs[program].hacking_level_required)
        .reduce((result, program) => {result[program] = programs[program]; return result}, {})
}

async function act(ns) {
    let flag_data = ns.flags([
        ["program", ""],
        ["callback", ""],
        ["all", false],
        ["help", false]
    ])

    let program = flag_data.program || flag_data._[0]
    let callback = flag_data.callback || flag_data._[1]
    let player = ns.getPlayer()
    let all = flag_data.all || program == "all"

    if (!program || flag_data.help) {
        usage(ns)
        runCallbackExit(ns, callback)
    }

    if (!all) {
        if (!Object.keys(programs).includes(program)) {
            ns.tprint(`${program} is not a valid program name, exiting...`)
            runCallbackExit(ns, callback)
        }

        if (ns.fileExists(program, "home")) {
            ns.tprint(`${program} already exists on home computer! exiting...`)
            runCallbackExit(ns, callback)
        }

        // Same v1 defect: `player.hacking` is undefined on a raw getPlayer()
        // result, so `undefined < n` is false and this guard never fired either.
        if ((player.skills?.hacking ?? 0) < programs[program].hacking_level_required) {
            ns.tprint(`${program} hacking level requirement (${programs[program].hacking_level_required}) not met (yours: ${player.hacking})`)
            runCallbackExit(ns, callback)
        }
    }

    while(true) {
        if (all) program = Object.keys(getCreateProgramTasks(ns)).shift()
        let startSuccess = ns.singularity.createProgram(program)
        if (startSuccess) {
            //await ns.sleep(programs[program].time)
            while (ns.singularity.isBusy()) await ns.sleep(EPSILON_WAIT_TIME)
        } else {
            ns.tprint(`Failed to start creating ${program} for an unknown reason.`)
            runCallbackExit(ns, flag_data.callback)
        }
        if (!all) break;
    }
    runCallbackExit(ns, flag_data.callback)
}
