// The stock trader's brain. Pure: no ns calls, free to import.
//
// stock.js feeds it one observation per market tick (ns.stock.nextUpdate) and
// executes the orders it returns. tools/sim/stocks/ runs the SAME functions
// against the game's own market code, which is where every constant below was
// chosen and where the claims in this header are measured (docs/stocks.md).
//
// ---------------------------------------------------------------------------
// THE MARKET, from ~/Repos/bitburner/src/StockMarket (v3.0.2)
//
//   StockMarket.ts:264-305  every 6s: one v = Math.random() SHARED by all 33
//                           stocks; av = v*mv/100; up (x(1+av)) with chance
//                           (50+otlkMag)/100 when bullish (b), down otherwise.
//   StockMarket.ts:223-236  every 75 ticks (one global counter, first length
//                           random 1..75) each stock flips b with chance 0.45 —
//                           its forecast f becomes 1-f.
//   Stock.ts:178-200        otlkMag drifts each tick by otlkMag*av toward the
//                           second-order forecast; the forecast is otherwise
//                           near-constant inside a cycle.
//   StockMarketHelpers.ts:463  each shareTxForMovement shares traded (either
//                           way) cut otlkMag by 0.006, floor 5. There is NO
//                           price impact in v3: the size limit on a position is
//                           maxShares and this forecast damage, nothing else.
//   Stock.ts:229-236        buy at ask = price(1+spread), sell at bid =
//                           price(1-spread); $100k commission per transaction.
//
// ---------------------------------------------------------------------------
// WHAT THIS DOES WITH IT
//
// 1. FORECAST. With 4S the forecast is read. Without it, it is ESTIMATED from
//    the up/down sequence each stock prints, which is an exact Bernoulli(f)
//    stream. The estimator knows the one structural fact that makes that
//    stream tractable: f only jumps at the global cycle boundary. So
//      - the boundary PHASE is learned once, jointly across all 33 stocks
//        (a flip in ~45% of them on the same tick is unmistakable), and
//      - per stock, the belief is a two-component Beta mixture that splits at
//        each boundary into "same" (0.55) and "flipped" (0.45) and lets the
//        next ticks decide which, instead of a sliding window that forgets
//        good data and learns flips late.
// 2. VOLATILITY. Never read (getVolatility is 2.5GB and 4S-only). The shared v
//    makes |ln(P_t/P_t-1)| = ln(1+v*mv/100) for every stock at once, so mv is
//    estimated from the price stream to a few percent within one cycle.
// 3. SIZING. No leverage exists, and Kelly's fraction for these walks is ~20x
//    capital, so the log-optimal policy is: be fully invested in the best
//    edges. The only limits are maxShares, the forecast damage our own
//    orders do (the marginal edge of the n-th share falls by 2*0.006*n/S), and
//    what the switch costs. So the portfolio is chosen greedily by MARGINAL
//    per-tick edge, where a held dollar competes at its edge and a new dollar
//    at its edge minus the round trip it has to pay.
// 4. SHORTS where the game allows them (BitNode 8 or SF8.2 — the caller says).

/** StockMarket/data/Constants.ts */
export const TICKS_PER_CYCLE = 75
export const FLIP_CHANCE = 0.45 // StockMarket.ts:229
export const COMMISSION = 100e3
export const IMPACT_PER_MOVE = 0.006 // StockMarketHelpers.ts:3 forecastChangePerPriceMovement (otlkMag points)
export const IMPACT_FLOOR = 5 // Stock.ts:5 StockForecastInfluenceLimit

/**
 * Per symbol: the midpoint of shareTxForMovement (InitStockMetadata.ts; the
 * real value is drawn in that range at every market init and is not readable
 * through the API) and the servers whose organizationName is the company
 * (Server/data/servers.ts) — the hack()/grow() targets that move its forecast.
 * Generated by tools/sim/stocks/gen-meta.mjs; tools/test/stockstrat.test.mjs
 * fails if it drifts from game source.
 */
export const SYMBOL_META = {
  ECP: { S: 60000, servers: ['ecorp'] },
  MGCP: { S: 60000, servers: ['megacorp'] },
  BLD: { S: 60000, servers: ['blade'] },
  CLRK: { S: 60000, servers: ['clarkinc'] },
  OMTK: { S: 60000, servers: ['omnitek'] },
  FSIG: { S: 60000, servers: ['4sigma'] },
  KGI: { S: 60000, servers: ['kuai-gong'] },
  FLCM: { S: 60000, servers: ['fulcrumtech', 'fulcrumassets'] },
  STM: { S: 72000, servers: ['stormtech'] },
  DCOMM: { S: 72000, servers: ['defcomm'] },
  HLS: { S: 72000, servers: ['helios'] },
  VITA: { S: 72000, servers: ['vitalife'] },
  ICRS: { S: 72000, servers: ['icarus'] },
  UNV: { S: 72000, servers: ['univ-energy'] },
  AERO: { S: 84000, servers: ['aerocorp'] },
  OMN: { S: 84000, servers: ['omnia'] },
  SLRS: { S: 84000, servers: ['solaris'] },
  GPH: { S: 84000, servers: ['global-pharm'] },
  NVMD: { S: 84000, servers: ['nova-med'] },
  WDS: { S: 33000, servers: [] },
  LXO: { S: 72000, servers: ['lexo-corp'] },
  RHOC: { S: 93000, servers: ['rho-construction'] },
  APHE: { S: 60000, servers: ['alpha-ent'] },
  SYSC: { S: 52500, servers: ['syscore'] },
  CTK: { S: 93000, servers: ['computek'] },
  NTLK: { S: 36000, servers: ['netlink'] },
  OMGA: { S: 60000, servers: ['omega-net'] },
  FNS: { S: 120000, servers: ['foodnstuff'] },
  SGC: { S: 45000, servers: ['sigma-cosmetics'] },
  JGN: { S: 33500, servers: ['joesguns'] },
  CTYS: { S: 48000, servers: ['catalyst'] },
  MDYN: { S: 153000, servers: ['microdyne'] },
  TITN: { S: 153000, servers: ['titan-labs'] },
}

/** Tunables. Every default here won a comparison in tools/sim/stocks/compare.mjs. */
export const DEFAULTS = {
  // Pre-4S forecast estimator: 'hmm' (exact Bayesian filter over a forecast
  // grid, one bank per candidate cycle phase — see observeHmm) or 'beta' (the
  // Beta-mixture + windowed phase score it replaced; kept for comparison).
  estimator: 'hmm',
  // hmm: per-tick chance the forecast drifts one grid step (1%) either way.
  diffusion: 0.01,
  // hmm: a phase bank is dropped when its posterior falls below this.
  phasePrune: 1e-7,
  // hmm: phase posterior above which ticksToBoundary trusts the phase.
  phaseTrust: 0.9,
  // Phase detection: windows either side of a candidate boundary, and the
  // log-evidence margin (nats) the best phase must hold over the runner-up
  // outside +-3 ticks before it is trusted.
  phaseWin: 12,
  phaseMargin: 12,
  // Pre-phase estimator: a Beta with this many pseudo-ticks of memory.
  preWindow: 30,
  // Within-cycle memory cap (pseudo-ticks) — lets slow otlkMag drift through.
  maxCount: 120,
  // Beta prior pseudo-counts (per side) at the very start.
  prior: 2,
  // Minimum |f-0.5| (posterior mean) before a NEW position is opened.
  minEdge: 0.02,
  // Ticks of the edge that a new position must be expected to earn, over and
  // above the round trip, before it is opened (guards estimator noise).
  entryHorizon: null, // null = expected ticks to the next flip (phase-aware)
  // Exit ahead of a boundary when the expected loss from a flip exceeds the
  // round trip (pre-4S only; with 4S a flip is seen one tick late).
  flipExit: true,
  // Do not trade a delta worth less than this fraction of the position (churn).
  minTradeFrac: 0.05,
  // Model our own forecast damage when sizing.
  impactAware: true,
  // New positions are valued at the posterior forecast pulled this many
  // standard deviations toward 0.5 (held ones at the mean): hysteresis sized
  // by how little the estimate is known, instead of a fixed margin.
  entryZ: 1,
  // Ticks of adverse moves before a pre-4S flip is believed.
  detectLag: 6,
  // A held chunk is displaced only by a candidate worth this much more (as a
  // fraction of the dollars moved, over the hold).
  switchMargin: 0.02,
  // A buy must be expected to earn this multiple of its two commissions.
  commissionCover: 2,
  // Cap on one stock as a fraction of wealth (1 = only maxShares limits).
  maxFrac: 1,
}

// ---------------------------------------------------------------------------
// math

const lnGamma = (() => {
  // Lanczos, g=7 — plenty for Beta-binomial ratios at counts <= a few hundred.
  const c = [0.99999999999980993, 676.5203681218851, -1259.1392167224028, 771.32342877765313, -176.61502916214059, 12.507343278686905, -0.13857109526572012, 9.9843695780195716e-6, 1.5056327351493116e-7]
  return function lg(x) {
    if (x < 0.5) return Math.log(Math.PI / Math.sin(Math.PI * x)) - lg(1 - x)
    x -= 1
    let a = c[0]
    const t = x + 7.5
    for (let i = 1; i < 9; i++) a += c[i] / (x + i)
    return 0.5 * Math.log(2 * Math.PI) + (x + 0.5) * Math.log(t) - t + Math.log(a)
  }
})()
export const lnBeta = (a, b) => lnGamma(a) + lnGamma(b) - lnGamma(a + b)

/**
 * log LR of "the stock flipped between window 1 and window 2" against "it did
 * not", each window's ups k of n, uniform prior on f. Under a flip, window 2's
 * downs are window 1's ups.
 */
export function flipLogLR(k1, n1, k2, n2) {
  const flip = lnBeta(1 + k1 + (n2 - k2), 1 + (n1 - k1) + k2)
  const same = lnBeta(1 + k1 + k2, 1 + (n1 - k1) + (n2 - k2))
  return flip - same
}

/**
 * Expected one-tick return of a position, from StockMarket.ts:293-300: the
 * price goes x(1+av) with chance f, /(1+av) otherwise; av = v*mv, v ~ U(0,1)
 * (mv as a fraction). E[av] = mv/2, E[av^2] = mv^2/3. Long gains the price
 * move; a short gains its negative (BuyingAndSelling/StockMarketHelpers:450).
 */
export function tickEdge(f, mv, side = 'L') {
  const ea = mv / 2
  const ea2 = (mv * mv) / 3
  const long = (2 * f - 1) * ea + (1 - f) * ea2
  return side === 'L' ? long : -long
}

// ---------------------------------------------------------------------------
// state

/**
 * `symbols`: the market's symbols (ns.stock.getSymbols()). `o`: DEFAULTS
 * overrides. `o.phase`: a known phase (tests/harness), else learned.
 */
export function newState(symbols, o = {}) {
  const opt = { ...DEFAULTS, ...o }
  const st = {
    opt,
    symbols: [...symbols],
    t: 0, // ticks observed
    phase: Number.isInteger(o.phase) ? o.phase : null, // t mod 75 of the first post-flip tick
    phaseFixed: Number.isInteger(o.phase),
    phaseScore: new Array(TICKS_PER_CYCLE).fill(0),
    phaseVotes4S: new Array(TICKS_PER_CYCLE).fill(0),
    lastPrice: {},
    hist: {}, // per symbol: array of 1/0 (up/down), newest last, bounded
    comps: {}, // per symbol: [{w,a,b}]
    absLnSum: {}, // per symbol: sum |ln ratio| (volatility)
    absLnN: 0,
    f4s: null, // last 4S forecasts when available
    f4sPrev: null,
    missed: 0,
  }
  for (const s of symbols) {
    st.hist[s] = []
    st.comps[s] = [{ w: 1, a: opt.prior, b: opt.prior }]
    st.absLnSum[s] = 0
  }
  if (opt.estimator === 'hmm') st.hmm = newHmm(symbols.length, st.phaseFixed ? [st.phase] : null)
  return st
}

// ---------------------------------------------------------------------------
// THE HMM ESTIMATOR (pre-4S)
//
// The hidden state of one stock is its forecast f, on a grid f = i/100. Per
// tick: (a) at a cycle boundary f -> 1-f with chance 0.45 (StockMarket.ts:
// 228-231), (b) a small diffusion for otlkMag drift (Stock.ts:178-200 — about
// otlkMag*av per tick, a fraction of a grid step), (c) the observation: up with
// chance f. That is an exact HMM given the boundary PHASE, which is shared by
// all 33 stocks and unknown, so there is one filter bank per candidate phase
// (75), each accumulating the log-likelihood of every stock's stream; the
// phase posterior is their softmax, and banks are pruned as it concentrates
// (after a few cycles only the true phase is left: 33 x 101 per tick).
// Cost before pruning: 75 x 33 x 101 multiply-adds per 6s tick — a few ms.

const GRID = 101
const FGRID = Float64Array.from({ length: GRID }, (_, i) => i / (GRID - 1))

/**
 * The stationary distribution of |f-0.5|*100 in bins of 5, measured on the
 * game's own market (tools/sim/stocks/fprior.mjs: 20 seeds, ticks 3000-30000).
 * Most stocks sit at otlkMag 5-10: the drift is x10 below 5 (Stock.ts via
 * StockMarket.ts:308-313), which empties the band near 0.5. A uniform prior
 * instead made a 4-tick streak look like f~0.8 and the phase filter lock onto
 * spurious boundaries within 6 ticks.
 */
export const F_PRIOR_BINS = [0.054, 0.5879, 0.2185, 0.0845, 0.0384, 0.0083, 0.0032, 0.002, 0.0017, 0.0014]
const PRIOR = (() => {
  const bin = (i) => Math.min(9, Math.floor(Math.abs(i - 50) / 5))
  const count = new Array(10).fill(0)
  for (let i = 0; i < GRID; i++) count[bin(i)]++
  const p = Float64Array.from({ length: GRID }, (_, i) => F_PRIOR_BINS[bin(i)] / count[bin(i)])
  const z = p.reduce((a, b) => a + b, 0)
  return p.map((x) => x / z)
})()

function newHmm(nSym, phases = null) {
  const alive = phases ?? Array.from({ length: TICKS_PER_CYCLE }, (_, i) => i)
  const banks = new Map()
  for (const ph of alive) {
    const P = new Float64Array(nSym * GRID)
    for (let j = 0; j < nSym; j++) P.set(PRIOR, j * GRID)
    banks.set(ph, { P, logL: 0 })
  }
  return { banks, post: new Map(alive.map((ph) => [ph, 1 / alive.length])) }
}

function observeHmm(st, ups) {
  const H = st.hmm
  const n = st.symbols.length
  const d = st.opt.diffusion
  const tmp = new Float64Array(GRID)
  for (const [ph, bank] of H.banks) {
    const P = bank.P
    const boundary = mod(st.t - ph, TICKS_PER_CYCLE) === 0
    let ll = 0
    for (let j = 0; j < n; j++) {
      const o = j * GRID
      // (a) flip at this bank's boundary, (b) diffusion
      for (let i = 0; i < GRID; i++) {
        let p = P[o + i]
        if (boundary) p = (1 - FLIP_CHANCE) * p + FLIP_CHANCE * P[o + GRID - 1 - i]
        tmp[i] = p
      }
      let z = 0
      const up = ups[j]
      for (let i = 0; i < GRID; i++) {
        const left = i > 0 ? tmp[i - 1] : tmp[i]
        const right = i < GRID - 1 ? tmp[i + 1] : tmp[i]
        const p = (1 - 2 * d) * tmp[i] + d * left + d * right
        // (c) observation
        const q = p * (up ? FGRID[i] : 1 - FGRID[i])
        P[o + i] = q
        z += q
      }
      if (!(z > 0)) {
        for (let i = 0; i < GRID; i++) P[o + i] = PRIOR[i]
        ll += Math.log(0.5)
        continue
      }
      for (let i = 0; i < GRID; i++) P[o + i] /= z
      ll += Math.log(z)
    }
    bank.logL += ll
  }
  // Phase posterior (uniform prior over the banks that were ever alive).
  let mx = -Infinity
  for (const b of H.banks.values()) if (b.logL > mx) mx = b.logL
  let Z = 0
  for (const b of H.banks.values()) Z += Math.exp(b.logL - mx)
  H.post = new Map()
  for (const [ph, b] of H.banks) H.post.set(ph, Math.exp(b.logL - mx) / Z)
  for (const [ph, w] of H.post) {
    if (w < st.opt.phasePrune && H.banks.size > 1) {
      H.banks.delete(ph)
      H.post.delete(ph)
    }
  }
  // Rebase log-likelihoods so they never overflow.
  for (const b of H.banks.values()) b.logL -= mx
}

function hmmMoments(st, s) {
  const H = st.hmm
  const j = st.symbols.indexOf(s)
  let m = 0
  let m2 = 0
  for (const [ph, b] of H.banks) {
    const w = H.post.get(ph) ?? 0
    if (w < 1e-9) continue
    const o = j * GRID
    for (let i = 0; i < GRID; i++) {
      const p = b.P[o + i] * w
      m += p * FGRID[i]
      m2 += p * FGRID[i] * FGRID[i]
    }
  }
  return { m, sd: Math.sqrt(Math.max(0, m2 - m * m)) }
}

/** The most probable phase and its posterior (hmm estimator). */
export function hmmPhase(st) {
  if (!st.hmm) return null
  let best = null
  for (const [ph, w] of st.hmm.post) if (!best || w > best.w) best = { phase: ph, w }
  return best
}

const HIST_MAX = 160

/**
 * Feed one market tick. `prices`: {sym: price} read after the tick;
 * `forecasts`: {sym: f} when 4S TIX API is owned, else null/undefined.
 * Returns nothing; mutates `st`.
 */
export function observe(st, prices, forecasts = null) {
  const o = st.opt
  const first = Object.keys(st.lastPrice).length === 0
  if (first) {
    for (const s of st.symbols) st.lastPrice[s] = prices[s]
    if (forecasts) st.f4s = { ...forecasts }
    return
  }
  // A tick in which NO price moved means the caller read twice between
  // updates; do not count it (every tick moves every price: av > 0 a.s.).
  let moved = 0
  for (const s of st.symbols) if (prices[s] !== st.lastPrice[s]) moved++
  if (moved === 0) {
    st.missed++
    return
  }
  const t = st.t + 1
  st.t = t
  const boundaryNow = st.phase !== null && mod(t - st.phase, TICKS_PER_CYCLE) === 0

  let lnSum = 0
  const ups = new Uint8Array(st.symbols.length)
  let jj = 0
  for (const s of st.symbols) {
    const p = prices[s]
    const r = Math.log(p / st.lastPrice[s])
    st.lastPrice[s] = p
    const up = r > 0 ? 1 : 0
    ups[jj++] = up
    st.absLnSum[s] += Math.abs(r)
    lnSum += Math.abs(r)
    const h = st.hist[s]
    h.push(up)
    if (h.length > HIST_MAX) h.shift()

    // Belief update. At a known boundary the belief splits first.
    let comps = st.comps[s]
    if (st.phase !== null) {
      if (boundaryNow) comps = splitAtBoundary(collapse(comps))
    } else {
      // No phase yet: a single Beta with bounded memory (a window).
      comps = [collapse(comps)]
      capCount(comps[0], o.preWindow)
    }
    for (const c of comps) {
      const m = c.a / (c.a + c.b)
      c.w *= up ? m : 1 - m
      if (up) c.a += 1
      else c.b += 1
      capCount(c, o.maxCount)
    }
    normalise(comps)
    st.comps[s] = comps.filter((c) => c.w > 1e-6)
  }
  st.absLnN++
  // The filter runs with or without 4S: when 4S is lost (it never is within a
  // node) or before it is bought, the phase is already known.
  if (st.hmm && !forecasts) observeHmm(st, ups)

  // Phase evidence from the direction streams: score the candidate boundary
  // `phaseWin` ticks back, now that the window after it is complete.
  const W = o.phaseWin
  const h0 = st.hist[st.symbols[0]]
  if (h0.length >= 2 * W) {
    const tau = t - W + 1 // candidate: first tick of the after-window
    let score = 0
    for (const s of st.symbols) {
      const h = st.hist[s]
      const n = h.length
      let k1 = 0
      let k2 = 0
      for (let i = n - 2 * W; i < n - W; i++) k1 += h[i]
      for (let i = n - W; i < n; i++) k2 += h[i]
      const lr = flipLogLR(k1, W, k2, W)
      score += Math.log(1 - FLIP_CHANCE + FLIP_CHANCE * Math.exp(Math.min(lr, 50)))
    }
    st.phaseScore[mod(tau, TICKS_PER_CYCLE)] += score
  }

  // With 4S a flip is visible directly: f -> 1-f on the boundary tick.
  if (forecasts) {
    st.f4sPrev = st.f4s
    st.f4s = { ...forecasts }
    if (st.f4sPrev) {
      let flips = 0
      for (const s of st.symbols) {
        const a = st.f4sPrev[s] - 0.5
        const b = st.f4s[s] - 0.5
        if (Math.abs(a) > 0.03 && a * b < 0 && Math.abs(a + b) < 0.02) flips++
      }
      if (flips >= 3) st.phaseVotes4S[mod(t, TICKS_PER_CYCLE)] += flips
    }
  }
  // Re-decided every tick, not locked: an early, marginal lock on a phase a
  // tick or two off (measured: 3 of 4 seeds) is corrected as evidence grows.
  if (!st.phaseFixed) {
    if (st.hmm && !forecasts) {
      const b = hmmPhase(st)
      st.phase = b && b.w >= st.opt.phaseTrust ? b.phase : st.phase
    } else {
      const p = decidePhase(st)
      if (p !== null) st.phase = p
    }
  }
}

function decidePhase(st) {
  // 4S votes: two boundaries agreeing is decisive.
  let best4 = -1
  let bi4 = -1
  for (let i = 0; i < TICKS_PER_CYCLE; i++) if (st.phaseVotes4S[i] > best4) (best4 = st.phaseVotes4S[i]), (bi4 = i)
  if (best4 >= 6) return bi4
  const sc = st.phaseScore
  let bi = 0
  for (let i = 1; i < TICKS_PER_CYCLE; i++) if (sc[i] > sc[bi]) bi = i
  let second = -Infinity
  for (let i = 0; i < TICKS_PER_CYCLE; i++) {
    const d = Math.min(mod(i - bi, TICKS_PER_CYCLE), mod(bi - i, TICKS_PER_CYCLE))
    if (d > 3 && sc[i] > second) second = sc[i]
  }
  if (sc[bi] > 0 && sc[bi] - second > st.opt.phaseMargin) {
    // The windowed score peaks within a tick or two of the truth; refine to
    // the neighbour with the largest score.
    return bi
  }
  return null
}

const mod = (a, n) => ((a % n) + n) % n

function capCount(c, cap) {
  const n = c.a + c.b
  if (n > cap) {
    c.a *= cap / n
    c.b *= cap / n
  }
}
function normalise(comps) {
  const z = comps.reduce((s, c) => s + c.w, 0)
  if (!(z > 0)) {
    for (const c of comps) c.w = 1 / comps.length
    return
  }
  for (const c of comps) c.w /= z
}
/** Moment-match a Beta mixture to one Beta, keeping the total count. */
function collapse(comps) {
  if (comps.length === 1) return { w: 1, a: comps[0].a, b: comps[0].b }
  let mean = 0
  let n = 0
  for (const c of comps) {
    mean += c.w * (c.a / (c.a + c.b))
    n += c.w * (c.a + c.b)
  }
  // If one component dominates, keep it as it is (the mixture is unimodal).
  const top = comps.reduce((x, c) => (c.w > x.w ? c : x))
  if (top.w > 0.9) return { w: 1, a: top.a, b: top.b }
  return { w: 1, a: mean * n, b: (1 - mean) * n }
}
function splitAtBoundary(c) {
  return [
    { w: 1 - FLIP_CHANCE, a: c.a, b: c.b },
    { w: FLIP_CHANCE, a: c.b, b: c.a },
  ]
}

/** Posterior mean forecast for a symbol (4S when present). */
export function forecastOf(st, s) {
  if (st.f4s && typeof st.f4s[s] === 'number') return st.f4s[s]
  if (st.hmm) return hmmMoments(st, s).m
  const comps = st.comps[s]
  let m = 0
  for (const c of comps) m += c.w * (c.a / (c.a + c.b))
  return m
}

/** Posterior standard deviation of the forecast (0 with 4S). */
export function forecastSd(st, s) {
  if (st.f4s && typeof st.f4s[s] === 'number') return 0
  if (st.hmm) return hmmMoments(st, s).sd
  let m = 0
  let m2 = 0
  for (const c of st.comps[s]) {
    const n = c.a + c.b
    const mu = c.a / n
    const v = (c.a * c.b) / (n * n * (n + 1))
    m += c.w * mu
    m2 += c.w * (v + mu * mu)
  }
  return Math.sqrt(Math.max(0, m2 - m * m))
}

/** Volatility estimate (fraction): E|ln(1+av)| ~ E[av] = mv/2. */
export function volOf(st, s) {
  if (!st.absLnN) return null
  return (2 * st.absLnSum[s]) / st.absLnN
}

/** Ticks until the next boundary (1..75), or null when the phase is unknown. */
export function ticksToBoundary(st) {
  if (st.phase === null) return null
  // The next tick is st.t+1; it is a boundary when (t - phase) % 75 === 0.
  return mod(st.phase - (st.t + 1), TICKS_PER_CYCLE) + 1
}

// ---------------------------------------------------------------------------
// the decision

/**
 * Expected ticks a freshly-opened position keeps its sign: to the next
 * boundary, then geometric in cycles (survives each with 0.55).
 */
export function expectedHold(st) {
  const r = ticksToBoundary(st) ?? TICKS_PER_CYCLE / 2
  return r - 1 + (TICKS_PER_CYCLE * (1 - FLIP_CHANCE)) / FLIP_CHANCE
}

/**
 * Decide this tick's orders.
 *
 * `book`: {
 *   cash,          money the trader may spend right now (after budget.js)
 *   positions:     {sym: [long, longAvg, short, shortAvg]}  (getPosition)
 *   maxShares:     {sym: n}
 *   ask, bid:      {sym: price}
 *   canShort:      boolean — BitNode 8 or SF8.2 (sfgate.canShortStock)
 *   liquidate:     true -> sell everything (install pending, claim due)
 *   raiseCash:     dollars that must be freed into cash this tick (claim)
 * }
 * Returns { orders: [{sym, kind: 'sell'|'cover'|'buy'|'short', shares, why}],
 *           targets, diag }.
 */
export function decide(st, book) {
  const o = st.opt
  const diag = { phase: st.phase, t: st.t, toBoundary: ticksToBoundary(st), pre4S: !st.f4s }
  const syms = st.symbols
  const sells = []
  const buys = []

  if (book.liquidate) {
    for (const s of syms) {
      const [L, , Sh] = book.positions[s]
      if (L > 0) sells.push({ sym: s, kind: 'sell', shares: L, why: 'liquidate' })
      if (Sh > 0) sells.push({ sym: s, kind: 'cover', shares: Sh, why: 'liquidate' })
    }
    return { orders: sells, diag: { ...diag, liquidate: true } }
  }

  const hold = o.entryHorizon ?? expectedHold(st)
  const tb = ticksToBoundary(st)
  const pre4S = !st.f4s
  const k = (s) => (o.impactAware ? IMPACT_PER_MOVE / (SYMBOL_META[s]?.S ?? 60000) : 0)
  // Per-tick edge per $ of the n-th share on `side` when otlkMag is M,
  // including the damage our own trading does (each S shares cut M by 0.006).
  const marginal = (s, side, mv, M, n) => {
    const Meff = M > IMPACT_FLOOR ? Math.max(IMPACT_FLOOR, M - 2 * k(s) * n) : M
    return tickEdge(0.5 + (side === 'L' ? 1 : -1) * (Meff / 100), mv, side)
  }
  // Pre-4S, holding across an imminent boundary risks a flip we learn late.
  const flipPenalty = (e) => (pre4S && o.flipExit && tb !== null && tb <= 2 ? FLIP_CHANCE * 2 * e * o.detectLag : 0)

  // ---- read the book -----------------------------------------------------
  const info = {}
  let wealth = book.cash
  for (const s of syms) {
    const [L, , Sh, shAvg] = book.positions[s]
    const bid = book.bid[s]
    const ask = book.ask[s]
    const mid = (bid + ask) / 2
    const vL = L > 0 ? L * bid - COMMISSION : 0
    const vS = Sh > 0 ? Sh * (2 * shAvg - ask) - COMMISSION : 0
    wealth += vL + vS
    const f = forecastOf(st, s)
    const mv = volOf(st, s)
    const sd = forecastSd(st, s)
    info[s] = { L, Sh, bid, ask, mid, spread: (ask - bid) / (2 * mid), f, mv, sd, max: book.maxShares[s] }
  }
  diag.wealth = wealth
  let cash = book.cash - Math.max(0, book.raiseCash ?? 0) - Math.max(0, book.reserve ?? 0)

  // ---- 1. exits: a position whose expected edge (posterior MEAN) is now
  // against it is closed. Entry demands the lower bound; exit the mean —
  // the band between them is the hysteresis that keeps noise from trading.
  const held = [] // chunks of what stays held, for the swap step
  for (const s of syms) {
    const x = info[s]
    if (x.mv === null) continue
    for (const side of ['L', 'S']) {
      const n = side === 'L' ? x.L : x.Sh
      if (!(n > 0)) continue
      const M = (side === 'L' ? x.f - 0.5 : 0.5 - x.f) * 100 // signed toward this side
      const e = M > 0 ? marginal(s, side, x.mv, M, n / 2) : tickEdge(x.f, x.mv, side)
      const wrongShort = side === 'S' && !book.canShort
      if (!(e - flipPenalty(Math.abs(e)) / hold > 0) || wrongShort) {
        sells.push({ sym: s, kind: side === 'L' ? 'sell' : 'cover', shares: n, why: `exit ${side}: f=${x.f.toFixed(3)}${wrongShort ? ' (shorting not allowed)' : ''}` })
        cash += side === 'L' ? n * x.bid - COMMISSION : n * (2 * (book.positions[s][3]) - x.ask) - COMMISSION
        continue
      }
      // Held chunks, least valuable first when swapping.
      const SL = 4
      const step = Math.ceil(n / SL)
      for (let a = 0; a < n; a += step) {
        const m = Math.min(step, n - a)
        const eh = marginal(s, side, x.mv, M, a + m / 2)
        held.push({ s, side, n: m, score: eh * hold - flipPenalty(eh), px: side === 'L' ? x.bid : x.ask })
      }
    }
  }

  // ---- 2. candidates: new shares on the favoured side, valued at the lower
  // confidence bound, net of the round trip they must pay.
  const cands = []
  for (const s of syms) {
    const x = info[s]
    if (x.mv === null) continue
    const side = x.f >= 0.5 ? 'L' : 'S'
    if (side === 'S' && !book.canShort) continue
    const Mlcb = Math.abs(x.f - 0.5) * 100 - o.entryZ * x.sd * 100
    if (Mlcb < o.minEdge * 100) continue
    const have = side === 'L' ? x.L : x.Sh
    const other = side === 'L' ? x.Sh : x.L
    const soldOther = sells.some((q) => q.sym === s)
    const room = x.max - have - (soldOther ? 0 : other) // maxShares counts both sides
    if (room <= 0) continue
    const cap = o.maxFrac < 1 ? Math.min(room, Math.max(0, Math.floor((o.maxFrac * wealth) / x.mid) - have)) : room
    const SL = 8
    const step = Math.max(1, Math.ceil(cap / SL))
    for (let a = 0; a < cap; a += step) {
      const m = Math.min(step, cap - a)
      const e = marginal(s, side, x.mv, Mlcb, have + a + m / 2)
      if (!(e > 0)) break
      const score = e * hold - flipPenalty(e) - 2 * x.spread
      if (!(score > 0)) break
      cands.push({ s, side, n: m, score, px: side === 'L' ? x.ask : x.bid })
    }
  }
  cands.sort((p, q) => q.score - p.score)
  held.sort((p, q) => p.score - q.score)

  const want = {} // s|side -> shares to buy
  const trim = {} // s|side -> shares to sell
  let hi = 0
  // ---- 3a. a claim that is due (raiseCash/reserve above the cash we hold)
  // is paid by selling the weakest held chunks first.
  while (cash < 0 && hi < held.length) {
    const h = held[hi]
    const take = Math.min(h.n, Math.ceil((-cash + COMMISSION) / h.px))
    trim[`${h.s}|${h.side}`] = (trim[`${h.s}|${h.side}`] ?? 0) + take
    cash += take * h.px - COMMISSION
    h.n -= take
    if (h.n <= 0) hi++
  }
  diag.raised = Object.keys(trim).length > 0

  // ---- 3b. fill from free cash, then 4. swap out the weakest held chunks
  // while a candidate beats them by the switch margin.
  for (const c of cands) {
    let need = c.n
    while (need > 0) {
      const dollars = need * c.px
      if (cash >= c.px) {
        const n = Math.min(need, Math.floor(cash / c.px))
        want[`${c.s}|${c.side}`] = (want[`${c.s}|${c.side}`] ?? 0) + n
        cash -= n * c.px
        need -= n
        continue
      }
      // No free cash: displace the weakest held chunk if clearly better.
      const h = held[hi]
      if (!h || h.s === c.s || !(c.score - h.score > o.switchMargin)) break
      const take = Math.min(h.n, Math.ceil(dollars / h.px))
      trim[`${h.s}|${h.side}`] = (trim[`${h.s}|${h.side}`] ?? 0) + take
      cash += take * h.px
      h.n -= take
      if (h.n <= 0) hi++
    }
    if (need > 0 && cash < c.px && !(held[hi] && c.score - held[hi].score > o.switchMargin)) break
  }

  // ---- 5. orders, with commission and churn guards.
  for (const [key, n] of Object.entries(trim)) {
    const [s, side] = key.split('|')
    sells.push({ sym: s, kind: side === 'L' ? 'sell' : 'cover', shares: n, why: `switch out ${side}: f=${info[s].f.toFixed(3)}` })
  }
  let spend = book.cash - Math.max(0, book.raiseCash ?? 0) - Math.max(0, book.reserve ?? 0)
  for (const q of sells) {
    const x = info[q.sym]
    spend += q.kind === 'sell' ? q.shares * x.bid - COMMISSION : q.shares * (2 * book.positions[q.sym][3] - x.ask) - COMMISSION
  }
  const buyList = Object.entries(want)
    .map(([key, n]) => {
      const [s, side] = key.split('|')
      const x = info[s]
      const px = side === 'L' ? x.ask : x.bid
      const Mlcb = Math.abs(x.f - 0.5) * 100 - o.entryZ * x.sd * 100
      const have = side === 'L' ? x.L : x.Sh
      const e = marginal(s, side, x.mv, Mlcb, have + n / 2)
      return { s, side, n, px, gain: n * px * (e * hold - 2 * x.spread), e }
    })
    .sort((p, q) => q.gain - p.gain)
  for (const b of buyList) {
    const have = b.side === 'L' ? info[b.s].L : info[b.s].Sh
    // Commission: the buy and its eventual sale must be paid for.
    if (!(b.gain > 2 * COMMISSION * o.commissionCover)) continue
    // Churn: topping up an existing position by a sliver is not worth a trade.
    if (have > 0 && b.n < o.minTradeFrac * have) continue
    let n = b.n
    if (n * b.px + COMMISSION > spend) n = Math.floor((spend - COMMISSION) / b.px)
    if (!(n > 0) || n * b.px * (b.e * hold) < 2 * COMMISSION * o.commissionCover) continue
    buys.push({ sym: b.s, kind: b.side === 'L' ? 'buy' : 'short', shares: n, why: `${b.side} f=${info[b.s].f.toFixed(3)}±${info[b.s].sd.toFixed(3)} edge ${(b.e * 1e4).toFixed(2)}bp/tick` })
    spend -= n * b.px + COMMISSION
  }
  diag.cash = cash
  return { orders: [...sells, ...buys], diag }
}
