// STAGED ns.ramOverride REWRITE of progress.js.
//
// Hand-written rather than generated by stage.mjs, because progress.js is the
// one candidate with a REAL ungated path: without Source-File 4 it still reads
// the player, checks TOR and the port programs, and writes /tel/todo.txt so a
// human knows what to click. That path has to keep working at a small
// allocation, so this file raises to one of TWO ceilings instead of returning.
//
// The original `main` body is preserved as `act(ns, canJoin)` with exactly ONE
// substantive change, described under "the probe" below.
//
// The `player.currentWork` / `player.focus` defects recorded in
// docs/game-knowledge.md §1 ARE now fixed, because wiring this file into
// watchdog.js made them live: getPlayer() returns neither field
// (NetscriptFunctions.ts:1371-1389), so `!work` was always true and every
// launch restarted focused faction work, and the refocus branch was
// unreachable. Under a supervisor that relaunches on an interval, that is a
// script stealing the UI every few minutes. Both now read through
// ns.singularity.getCurrentWork / isFocused. `player.factionInvitations` is
// still absent from getPlayer(), but the acting path already sources
// invitations from sing.checkFactionInvitations(); only the SF4-less advisory
// fallback reads the missing field, and it degrades to "no invitations".
//
// ---------------------------------------------------------------------------
// RAMOVERRIDE 2.6GB — excludes: every ns.singularity.* call in this file —
// getOwnedAugmentations / purchaseAugmentation / installAugmentations /
// getAugmentationsFromFaction (5GB each at base price, 80GB each at the 16x
// SF4.1 rate), workForFaction / checkFactionInvitations / joinFaction (3/48GB),
// getAugmentationRepReq / getAugmentationPrice (2.5/40GB), purchaseTor /
// purchaseProgram (2/32GB), getFactionRep (1/16GB) and setFocus (0.1/1.6GB) —
// and also ns.getPlayer, ns.hasTorRouter, ns.fileExists and
// ns.getServerMoneyAvailable, which the advisory path does use but only AFTER
// the allocation has been raised to RAISE_CEILING(0).
//
// 2.6 = RamCostConstants.Base (1.6) + ns.getResetInfo (1.0): everything called
// before the capability decision. sfgate.js is pure and status.js touches only
// ns.write (0GB).
//
// TWO ceilings, both raised through ramgrow.js before any of the excluded calls:
//   RAISE_CEILING(0)     the advisory path — every non-singularity call in the
//                        file, and nothing else. This is what makes a BitNode
//                        with no SF4 able to run progress.js at all; the shipped
//                        file costs 627.95GB there and simply cannot be started.
//   RAISE_CEILING(mult)  the acting path — the file's full static price at this
//                        save's Singularity RAM multiplier (sfgate.js:71-77).
//
// THE PROBE. The shipped file decides capability by CALLING a singularity
// function inside a try/catch (`capable(ns, () => sing.getOwnedAugmentations(false))`).
// That cannot survive an override: APIWrapper.ts:80 charges the call's RAM
// BEFORE the body runs, so the probe alone costs 5GB (80GB at SF4.1) and
// NetscriptHelpers.tsx:523 calls killWorkerScript before it throws — the catch
// runs but the script is already dead. The probe is therefore replaced by
// `canUseSingularity(info)`, which is the SAME predicate the game itself uses:
// checkSingularityAccess (NetscriptHelpers.tsx:438-446) is a bare
// `canAccessBitNodeFeature(4)`, and sfgate.js:63 is that rule. Invariant SF3 —
// the gate is not open-coded here.
//
// Registered in tools/sim/bncheck.mjs STRUCTURAL. Asserted by
// tools/test/ramoverride.test.mjs [R1..R5].
// ---------------------------------------------------------------------------
// Drives progression: joins factions, works for reputation, buys programs and
// augmentations, and installs — automatically where the game allows it, and by
// telling a human exactly what to click where it does not.
//
//   run progress.js              act where possible, report the rest
//   run progress.js --dry        decide and report, change nothing
//   run progress.js --no-install never install, even when the trigger is met
//
// ---------------------------------------------------------------------------
// Why it is written this way
//
// Almost everything a player does outside a terminal — joining a faction,
// working for reputation, buying a program, upgrading home RAM, purchasing an
// augmentation, installing — lives behind `ns.singularity.*`, which requires
// Source-File 4. In a BitNode where SF4 is absent those actions cannot be
// scripted at all, and the progression stalls silently: the fleet keeps
// earning, the level keeps climbing, and reputation sits at zero because
// nobody clicked anything.
//
// So this script does not assume either world. It probes for each capability
// once, uses what is available, and writes what it could not do to
// /tel/todo.txt so the gap is visible instead of silent. The same file works
// unchanged on a fresh BitNode 1 with nothing and on a late run with every
// Source-File — it simply does more of the work itself as more becomes
// available.
// ---------------------------------------------------------------------------

const STATUS = '/tel/progress.txt'
const TODO = '/tel/todo.txt'
const GATE = '/tel/installgate.txt'

import { canUseSingularity, singularityRamMultiplier } from 'sfgate.js'
import { reporter } from 'status.js'
import { raiseRam } from 'ramgrow.js'
import { shouldInstall, progressFactor } from 'installgate.js'
import { planPurchases, NFG, isSoa, BASE_PRICE_MULT } from 'augplan.js'

/** This file's static price as a function of the Singularity RAM multiplier.
 *  RAISE_CEILING(0) is every non-singularity call in the file; the second term
 *  is the ns.singularity surface at base price. Both measured with the game's
 *  own calculator; re-checked on every run by ramoverride.test.mjs [R5], which
 *  fails if the ceiling does not reach the full static price in any regime. */
// 39.1 -> 39.7: reading the work state properly added ns.singularity
// getCurrentWork (0.5 base) and isFocused (0.1 base), both scaled by the
// Singularity multiplier. Asserted against the game's own calculator by
// tools/test/ramoverride.test.mjs [R1..R5] — if this number drifts from the
// file's real static price the raise is short, and a short raise is SILENTLY
// denied (NetscriptFunctions.ts:1210-1214 returns the old allocation), so the
// test is the only thing standing between a wrong constant and a script that
// dies mid-run for no visible reason.
// 39.7 -> 49.7, and TWO separate reasons, only one of which is this change.
//
// (1) +5.0 for ns.singularity.getAugmentationPrereq (RamCostGenerator.ts:205,
//     SingularityFn3 = 5GB base, scaled by the SF4 RAM multiplier). Without it
//     the planner cannot see prerequisites, and descending PRICE order puts
//     "Cranial Signal Processors - Gen V" before Gen I, so the purchase is
//     rejected (FactionHelpers.tsx:88-95) and purchaseAugmentation returns false
//     with nothing reporting it.
//
// (2) +5.0 THAT WAS ALREADY MISSING. The shipped constant is 39.7 and the
//     shipped file's real static price is 44.7 per multiplier unit — measured
//     at 48.05GB in BitNode 4 and 718.55GB at SF4.1 by BOTH tools/test/ram.mjs
//     (priceOverlay, the game's own calculateRamUsage) and
//     tools/staging/ramcheck.mjs, which agree exactly. So the deployed ceiling
//     is 43.05 against a 48.05 requirement: 5GB short in BN4 and 80GB short at
//     SF4.1. A short raise is SILENTLY denied (NetscriptFunctions.ts:1210-1214
//     returns the old allocation) and the script then dies mid-run with no
//     signal. It is dormant today only because this save has no Source-File 4,
//     so canJoin is false and the advisory ceiling RAISE_CEILING(0) = 3.35 is
//     the one used — and 3.35 is correct. It breaks the day SF4 arrives.
//
//     tools/test/ramoverride.test.mjs [R5] does not catch it because its subject
//     is tools/staging/ramoverride/progress.js, which is stale: that copy still
//     says 39.1 and lacks getAugmentationStats, getCurrentWork and isFocused —
//     exactly the 5.6GB of calls the root file gained. R5 reports "progress.js
//     BN4 full 42.45GB" and passes, while the file that actually runs costs
//     48.05GB. A test checking a copy of the thing it guards.
//
// 49.7 is MEASURED, not arithmetic: priceOverlay puts this file at 53.05GB in
// BN4 (= 3.35 + 49.7) and 798.55GB at SF4.1 (= 3.35 + 49.7*16).
const RAISE_CEILING = (mult) => 3.35 + 49.7 * mult

export async function main(ns) {
  ns.ramOverride(2.6)

  // This reporter covers the paths that would otherwise produce silence.
  const note = reporter(ns, STATUS, {})

  // ns.atExit, added when progress.js entered watchdog.js's WATCHED list
  // (invariant C1: every managed script publishes on return, handled error,
  // throw AND kill).
  //
  // The original note here said an exit hook was deliberately omitted, because
  // act() writes /tel/progress.txt as its last statement and a reporter
  // republishing over it would change the shape readers parse. That reasoning
  // held while nothing supervised this file. It does not hold now: the kill
  // path writes nothing at all, and a managed script that dies silently is
  // indistinguishable from one that is merely between runs — precisely the
  // gap that let "no faction joined" persist for nine hours.
  //
  // The conflict is resolved by making the hook CONDITIONAL rather than
  // unconditional. `finished` is set only after act() has published its own
  // report, so the normal path still leaves act()'s richer shape untouched and
  // the hook fires only on kill, throw, or an install that never returns.
  // ns.atExit is 0GB and runs before teardown (killWorkerScript.ts:64-84), so
  // the write lands. Explicit id so it cannot displace lock.js's 'ui-lock'.
  let finished = false
  ns.atExit(() => {
    if (finished) return
    note.exit('stopped', {
      detail: 'progress.js exited without publishing — killed, threw, or installed augmentations',
    })
  }, 'status')

  const info = ns.getResetInfo()
  const canJoin = canUseSingularity(info)
  const want = canJoin ? RAISE_CEILING(singularityRamMultiplier(info)) : RAISE_CEILING(0)

  if (!raiseRam(ns, want, STATUS, canJoin ? 'progress.js acting path' : 'progress.js advisory path')) return

  try {
    const r = await act(ns, canJoin, info)
    finished = true
    return r
  } catch (err) {
    // The shipped file has no catch at all, so a throw anywhere in it produced
    // nothing but a dead process. Publish, then rethrow so nothing is hidden.
    note('error', { result: 'error', canJoin, allocation: want, detail: String(err) })
    // Mark published BEFORE rethrowing. The atExit hook fires after this and
    // would otherwise overwrite a report naming the actual exception with the
    // generic "exited without publishing" — turning a precise diagnosis into a
    // vaguer one, which is the opposite of what the hook is for.
    finished = true
    throw err
  }
}


/*
 * REMOVED: `capable(ns, fn)`, the try/catch probe.
 *
 * The shipped file's reasoning was "there is no 'do I have Source-File 4' API
 * that does not itself cost RAM, so the honest test is to call the thing and
 * see whether it throws." Both halves are wrong now:
 *
 *  - ns.getResetInfo() costs 1.0GB and answers it exactly. The game's own gate,
 *    checkSingularityAccess (NetscriptHelpers.tsx:438-446), is a bare
 *    canAccessBitNodeFeature(4), which is sfgate.js:63.
 *  - the probe is FATAL under an ns.ramOverride: APIWrapper.ts:80 charges the
 *    call's RAM before its body runs, and NetscriptHelpers.tsx:523 calls
 *    killWorkerScript(ws) before throwing — so the catch runs in a process that
 *    is already dead. A 5GB (80GB at SF4.1) probe to learn something a 1GB call
 *    already knows.
 *
 * The 'SF may be present at level 1 with some calls gated higher' worry does not
 * apply: every ns.singularity function goes through the same level-free gate.
 */

/** Factions that sell hacking augmentations, best first for our purposes. */
const HACK_FACTIONS = [
  'Daedalus',
  'BitRunners',
  'The Black Hand',
  'NiteSec',
  'CyberSec',
  'Netburners',
]

/** Never join these without a reason: they conflict with other city factions. */
const CITY_FACTIONS = ['Sector-12', 'Aevum', 'Volhaven', 'Chongqing', 'New Tokyo', 'Ishima']

async function act(ns, canJoin, info) {
  const flags = ns.flags([
    ['dry', false],
    ['no-install', false],
  ])
  ns.disableLog('ALL')

  const todo = []
  const did = []

  const player = ns.getPlayer()
  const sing = ns.singularity

  // --- capability probes, each cheap and done once ---------------------------
  // `canJoin` is now passed in from main(), derived through sfgate.js rather
  // than by calling a singularity function and catching the throw. See "THE
  // PROBE" in this file's header: under an ns.ramOverride the old probe was
  // fatal, because the call's RAM is charged before its body runs.
  const canWork = canJoin && typeof sing.workForFaction === 'function'
  const canBuyAug = canJoin && typeof sing.purchaseAugmentation === 'function'
  const canInstall = canJoin && typeof sing.installAugmentations === 'function'

  // --- 1. accept invitations -------------------------------------------------
  const invites = canJoin ? sing.checkFactionInvitations() : (player.factionInvitations ?? [])
  const wanted = invites.filter((f) => !CITY_FACTIONS.includes(f))
  for (const f of wanted) {
    if (canJoin && !flags.dry) {
      if (sing.joinFaction(f)) did.push(`joined ${f}`)
    } else {
      todo.push(`Accept the ${f} invitation (Factions tab).`)
    }
  }
  for (const f of invites.filter((f) => CITY_FACTIONS.includes(f))) {
    todo.push(`${f} invite pending — a city faction. Joining splits contract reputation and conflicts with the other cities. Left alone deliberately.`)
  }

  // --- 2. make sure reputation is actually being earned ----------------------
  // This is the failure that matters most: with no faction work running, the
  // one quantity that cannot be bought earns nothing, and everything else in
  // the game looks perfectly healthy while it happens.
  const factions = canJoin ? sing.getOwnedAugmentations && player.factions : player.factions

  // READ THE WORK STATE FROM SINGULARITY, NOT FROM getPlayer().
  //
  // This used to be `player.currentWork`, and `ns.getPlayer()` does not return
  // that field: NetscriptFunctions.ts:1371-1389 builds the payload by hand and
  // it carries hp/skills/exp/mults/city/numPeopleKilled/money/location/
  // totalPlaytime/jobs/factions/entropy/karma — and nothing else. So `work` was
  // ALWAYS undefined, `!work` was ALWAYS true, and this branch called
  // workForFaction on every single launch.
  //
  // That is silent in the worst way. Reputation still accrues, so the telemetry
  // says "working for X, focused" and looks correct; what actually happens is
  // that each launch restarts the work and re-steals UI focus. Under a watchdog
  // that relaunches on an interval, that is a script taking over the screen
  // every few minutes for no benefit — the same failure shape as homeup.js.
  //
  // `player.focus` is absent from the same payload, which made the refocus
  // branch below unreachable: `undefined === false` is false, so an unfocused
  // faction work session was never corrected despite costing 20% of the rate.
  const work = canJoin ? sing.getCurrentWork() : null

  if (!factions || factions.length === 0) {
    todo.push('NO FACTION JOINED — reputation is earning ZERO. Backdoor a story server (run findpath.js <server>) and accept the invite.')
  } else if (!work || work.type !== 'FACTION') {
    const target = HACK_FACTIONS.find((f) => factions.includes(f)) ?? factions[0]
    if (canWork && !flags.dry) {
      if (sing.workForFaction(target, 'hacking', true)) did.push(`working for ${target}, focused`)
      else todo.push(`Could not start faction work for ${target} — start it manually.`)
    } else {
      todo.push(`NO FACTION WORK RUNNING — reputation is earning ZERO. Start hacking contracts for ${target} and FOCUS it (unfocused costs 20%).`)
    }
  } else if (canWork && !sing.isFocused()) {
    if (canWork && !flags.dry) {
      sing.setFocus(true)
      did.push('refocused faction work')
    } else {
      todo.push('Faction work is UNFOCUSED — costs 20% of the rate. Click Focus, then verify a few seconds later; it has been seen reverting.')
    }
  }

  // --- 3. port programs ------------------------------------------------------
  // Each one unlocks a tier of servers to root, and rooting is gated on open
  // ports alone, never on hacking level — so they are worth buying the moment
  // they are affordable, at any level.
  const PROGRAMS = [
    ['BruteSSH.exe', 500e3],
    ['FTPCrack.exe', 1.5e6],
    ['relaySMTP.exe', 5e6],
    ['HTTPWorm.exe', 30e6],
    ['SQLInject.exe', 250e6],
  ]
  // The game's own predicate; serverExists('darkweb') is always true.
  const hasTor = ns.hasTorRouter()
  if (!hasTor) {
    if (canJoin && !flags.dry && ns.getServerMoneyAvailable('home') > 200e3) {
      if (sing.purchaseTor()) did.push('bought TOR')
    } else todo.push('Buy the TOR router ($200k) — gates every port program.')
  }
  for (const [file, price] of PROGRAMS) {
    if (ns.fileExists(file, 'home')) continue
    if (canJoin && !flags.dry && ns.getServerMoneyAvailable('home') > price * 2) {
      if (sing.purchaseProgram(file)) did.push(`bought ${file}`)
    } else if (ns.getServerMoneyAvailable('home') > price) {
      todo.push(`Buy ${file} ($${(price / 1e6).toFixed(1)}m) — unlocks a tier of servers to root.`)
    }
  }

  // --- 4. PLAN the augmentations; do not buy yet -----------------------------
  //
  // THE CHANGE. The shipped loop sorted `offers` by price descending and bought
  // whatever was affordable on THIS pass. Three defects, all of them silent:
  //
  //   (i)  it bought ACROSS TIME rather than planning a set. The k-th purchase
  //        of an install cycle costs `intrinsic * 1.9^k`
  //        (AugmentationHelpers.ts:32-37,157), so rank 0 is the most valuable
  //        position there is — and a five-minute pass spent it on whatever
  //        happened to be affordable at the time.
  //   (ii) it ranked by PRICE, not by VALUE. On the real BitNode 4 catalogue
  //        that buys Neuralstimulator at $3,000m — hacking_chance, hacking_speed
  //        and hacking_grow, none of which appear in installgate.js's
  //        RATE_CHANNELS — at rank 0, for a multiplier gain of exactly zero.
  //        Measured: tools/staging/augplan/measure.mjs.
  //   (iii) it ignored prerequisites. `purchaseAugmentation` returns false when
  //        a prereq is unmet (FactionHelpers.tsx:88-95) and the loop moves on,
  //        so an augmentation we have the reputation and the money for is simply
  //        never bought and nothing says so.
  //
  // augplan.js owns the economics now, exactly as installgate.js owns the
  // install decision. This section only gathers what it needs.
  //
  // PRICES ARE LIVE, NOT BASE. getAugmentationPrice has already applied
  // 1.9^(queued non-SoA) and the BitNode multiplier. With the plan-now-buy-later
  // architecture nothing is queued at plan time, so the live price IS the rank-0
  // intrinsic — but not on the first pass after a deploy, or after a partially
  // executed plan. So the queued count is measured and divided back out, and
  // `nodeMoneyMult` is left at 1 because the live price already carries it.
  let plan = null
  if (canBuyAug) {
    const count = (list) => list.reduce((m, a) => m.set(a, (m.get(a) ?? 0) + 1), new Map())
    const installedCount = count(sing.getOwnedAugmentations(false))
    const allCount = count(sing.getOwnedAugmentations(true))
    const held = []
    for (const [name, n] of allCount) {
      for (let i = 0; i < n - (installedCount.get(name) ?? 0); i++) held.push(name)
    }
    const r = BASE_PRICE_MULT // SF11 is not held; genericPriceMultiplier(lvl) when it is
    const unqueue = Math.pow(r, held.filter((a) => !isSoa(a)).length)

    const offers = []
    for (const f of player.factions) {
      const rep = sing.getFactionRep(f)
      for (const aug of sing.getAugmentationsFromFaction(f)) {
        // NeuroFlux is the only repeatable augmentation (AugmentationHelpers.ts:117-120).
        if (allCount.has(aug) && aug !== NFG) continue
        offers.push({
          name: aug,
          faction: f,
          baseCost: sing.getAugmentationPrice(aug) / (isSoa(aug) ? 1 : unqueue),
          repReq: sing.getAugmentationRepReq(aug),
          factionRep: rep,
          mults: sing.getAugmentationStats(aug),
          prereqs: sing.getAugmentationPrereq(aug),
          // The live NFG price already carries 1.14^getLevel(), so the planner
          // starts its own chain at 0 rather than double-counting the level.
          nfgLevel: 0,
        })
      }
    }

    plan = planPurchases({
      offers,
      money: ns.getServerMoneyAvailable('home'),
      r,
      nodeMoneyMult: 1, // already in the live price
      owned: [...installedCount.keys()],
      soaOwned: [...allCount.keys()].filter(isSoa).length,
    })
    // A planner that silently fell back to a heuristic must say so, every pass.
    if (!plan.exact) did.push(`plan is APPROXIMATE: ${plan.approximation}`)
    for (const rgroup of plan.restricted) did.push(`plan restricted: ${rgroup.why} (${rgroup.group.join(' -> ')})`)
  } else {
    todo.push('Augmentation purchases need Source-File 4 — buy them in the Factions UI, MOST EXPENSIVE FIRST (money cost multiplies 1.9x per already-queued aug; reputation cost does not), and buy a prerequisite BEFORE the augmentation that needs it.')
  }

  // --- 5. the gate, then execute the plan and install ------------------------
  //
  // THE CHICKEN AND EGG, and its fix.
  //
  // installgate.js decides on `M` over the QUEUED augmentations. Move purchasing
  // to "plan now, buy at install time" and nothing is ever queued, so M is always
  // 1, `shouldInstall` returns "the queued augmentations give no gain", and the
  // gate NEVER FIRES. The run would then accumulate money forever and never
  // install — which in a node whose exit is multiplier-bound is the single worst
  // failure mode available (installgate.js, "a gate that refuses to install is
  // not conservative — it is the failure mode").
  //
  // The fix is to evaluate the PLANNED set rather than the queued set. That is
  // strictly better than the old behaviour, not merely equivalent:
  //
  //   - it is forward-looking. The gate sees what the money COULD buy, including
  //     a threshold reputation has just crossed, before a dollar is committed.
  //   - the marginal-versus-average rule is unchanged. Planned M rises for
  //     exactly the reasons queued M used to rise (money accumulating,
  //     reputation crossing requirements) and flattens for exactly the reasons
  //     it used to flatten — so `d ln(M)/dt < ln(M)/A` still means "accumulation
  //     has stalled, cash in".
  //   - it removes the reason the old loop was wrong. Nothing is bought
  //     opportunistically at minute 5 and then repriced at 1.9x for everything
  //     that follows.
  //
  // M IS THE PRODUCT OF BOTH SETS. Anything already queued from a previous pass
  // (or from a partially executed plan) will also be installed, so it counts —
  // planned M alone would under-report and the gate would hold on a queue it
  // should be cashing in.
  //
  // THE THRASH GUARD STILL HOLDS, for a different reason than before.
  // installgate.js's header argues the gate cannot fire twice in a row because
  // an install sets money to $1,262 (PlayerObjectGeneralMethods.ts:102) and M is
  // therefore 1. Under this change the argument becomes "nothing is affordable
  // at $1,262, so the PLAN is empty and M is 1". That is still true, but it is
  // now a property of the planner rather than of the queue — so it is asserted
  // in tools/staging/augplan/augplan.test.mjs [AP9] instead of left as prose.
  const count = (list) => list.reduce((m, a) => m.set(a, (m.get(a) ?? 0) + 1), new Map())
  let pending = []
  if (canBuyAug) {
    // MULTISET difference, not a Set difference. getOwnedAugmentations(true)
    // returns installed names CONCATENATED with queued names, duplicates
    // included (Singularity.ts:79-90). NeuroFlux Governor is stackable, so with
    // a Set every queued NeuroFlux was discarded — four of them (M = 1.1268)
    // reported as M = 1.0000, and the gate held on evidence it should have
    // counted.
    const installed = count(sing.getOwnedAugmentations(false))
    for (const [name, n] of count(sing.getOwnedAugmentations(true))) {
      for (let i = 0; i < n - (installed.get(name) ?? 0); i++) pending.push(name)
    }
  }

  const heldM = progressFactor(pending.map((a) => sing.getAugmentationStats(a)))
  const M = heldM * (plan ? plan.M : 1)
  const total = pending.length + (plan ? plan.buy.length : 0)

  if (total > 0) {
    // installgate.js owns the decision. The rule is marginal-versus-average on
    // ln(M)/A, so it needs the PREVIOUS sample — which means this file has to
    // persist one between runs. progress.js is a job: it exits after every
    // pass, so nothing survives in memory.
    let prev = null
    try {
      const saved = JSON.parse(ns.read(GATE) || 'null')
      // Only a sample from THIS life is meaningful. lastAugReset moves on every
      // install, so a sample whose age exceeds ours belongs to a previous life
      // and would make the marginal rate nonsense.
      if (saved && saved.sample && saved.lastAugReset === info?.lastAugReset) prev = saved.sample
    } catch {
      /* absent or mid-write; treated as no previous sample, which only defers */
    }

    const gate = shouldInstall({
      ageMs: Date.now() - (info?.lastAugReset ?? 0),
      M,
      queued: total,
      prev,
    })

    // Persist BEFORE acting. An install never returns, so a write afterwards
    // would never happen and the next life would start with no history — and
    // the lastAugReset stamp is what stops that stale sample being reused.
    // The plan goes in the file too: "what would we have bought, and what was
    // one faction errand away" is the question this file is asked after the
    // fact, and it cannot be reconstructed from the save.
    ns.write(
      GATE,
      JSON.stringify(
        {
          at: new Date().toISOString(),
          lastAugReset: info?.lastAugReset,
          pending,
          heldM,
          plannedM: plan ? plan.M : 1,
          plan: plan ? { buy: plan.buy, totalCost: plan.totalCost, exact: plan.exact, stats: plan.stats, skipped: plan.skipped.slice(0, 20) } : null,
          ...gate,
        },
        null,
        2,
      ),
      'w',
    )

    if (!canInstall || flags['no-install'] || flags.dry) {
      todo.push(`${pending.length} queued + ${plan ? plan.buy.length : 0} planned (M=${M.toFixed(4)}) — ${gate.why}`)
    } else if (gate.install) {
      // EXECUTE THE PLAN, IN ORDER, RE-PRICING AS WE GO.
      //
      // A plan is computed from a snapshot and money moves between the snapshot
      // and the spend. Buying blind against a stale price is the "plan that
      // cannot be executed, discovered by failing" shape in CLAUDE.md's table —
      // planBatch's 7,274 placement failures reporting health: stalled. So each
      // purchase re-reads the price the game will actually charge and stops if
      // it has drifted, rather than silently buying something else at a rank the
      // plan never priced.
      const bought = []
      if (plan) {
        for (const item of plan.buy) {
          const live = sing.getAugmentationPrice(item.name)
          const drift = Math.abs(live - item.price) / Math.max(item.price, 1)
          if (drift > 0.01) {
            did.push(`STOPPED executing the plan at ${item.name}: planned $${item.price.toFixed(0)}, game says $${live.toFixed(0)} (${(drift * 100).toFixed(1)}% drift) — the plan is stale`)
            break
          }
          if (ns.getServerMoneyAvailable('home') < live) {
            did.push(`STOPPED executing the plan at ${item.name}: $${live.toFixed(0)} needed, $${ns.getServerMoneyAvailable('home').toFixed(0)} held — the plan over-spent`)
            break
          }
          if (!sing.purchaseAugmentation(item.faction, item.name)) {
            // The shipped file ignored this return value entirely, which is how
            // a prerequisite failure stayed invisible.
            did.push(`REFUSED by the game: ${item.name} from ${item.faction} — rep, money or an unmet prerequisite`)
            break
          }
          bought.push(item.name)
        }
      }
      const installing = pending.length + bought.length
      ns.write(STATUS, JSON.stringify({ at: new Date().toISOString(), did, bought, installing, gate }, null, 2), 'w')
      did.push(`bought ${bought.length} of ${plan ? plan.buy.length : 0} planned; installing ${installing} augmentation(s) — ${gate.why}`)
      if (installing === 0) {
        // Nothing to install and nothing bought: do NOT call installAugmentations,
        // which would prestige for no gain. Say so instead.
        todo.push('the gate fired but no augmentation could be bought — check /tel/installgate.txt for the plan and why each purchase was refused')
      } else {
        sing.installAugmentations('boot.js')
        return // the game reloads; boot.js brings the stack back up
      }
    } else {
      // Holding is a decision, not silence: published every pass with the
      // numbers behind it, so a gate that is stuck can be told from one that is
      // correctly waiting.
      did.push(gate.why)
      if (plan && plan.skipped.length) {
        const near = plan.skipped.filter((s) => s.why === 'reputation').sort((a, b) => a.short - b.short)[0]
        if (near) todo.push(`${Math.round(near.short).toLocaleString()} more ${near.faction} reputation unlocks ${near.name}`)
      }
    }
  }

  const report = { at: new Date().toISOString(), capabilities: { canJoin, canWork, canBuyAug, canInstall }, did, todo }
  ns.write(STATUS, JSON.stringify(report, null, 2), 'w')
  ns.write(TODO, JSON.stringify({ at: report.at, todo }, null, 2), 'w')

  for (const d of did) ns.tprint(`progress: ${d}`)
  for (const t of todo) ns.tprint(`progress: TODO ${t}`)
  if (!did.length && !todo.length) ns.tprint('progress: nothing to do')
}
